### ISSUE TITLE
run/CM4_run_script.sh doesn't match README documentation.

### ISSUE THREAD

**Issue by russfiedler** [NOAA-GFDL/CM4#1]
Just a minor issue. It looks like there was a commit while the `run/CM4_run_script.sh` was being edited.

The README.md says

"The sample data and run script are configured to run on a total of 8127 processors (864 cores 4 threads for the atmosphere and 4671 ocean cores)."

However this doesn't match  https://github.com/NOAA-GFDL/CM4/blob/master/run/CM4_run_script.sh#L31-L38

There's also a rogue vi .swp file in the run directory. It looks like this contains the intended configuration changes.

**Comment by thomas-robinson** [comment]
Thanks for pointing it out @russfiedler .  I knew I would inevitably miss something.
