### ISSUE TITLE
Damaged file of CM4_runDir.tar.gz

### ISSUE THREAD

**Issue by miniufo** [NOAA-GFDL/CM4#12]
Hi sir,

I am currently interested in using the CM4 model to study the impact of mixing on climate.  After the model is compiled, I download [the input data](ftp://nomads.gfdl.noaa.gov/users/Isaac.Held/CM4Documentation/GFDL-CM4.0/inputData) as suggested on this repo.  However, when I try to extract the file from the tar ball, using `tar -zxvf CM4_runDir.tar.gz`, I get the error:
>gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

I am not sure this file has been damaged somehow during preparation or during downloading (I tried to download this file three times).  Could you please give a test on the tar ball file?

**Comment by thomas-robinson** [comment]
@miniufo I just downloaded the file ftp://nomads.gfdl.noaa.gov/users/Isaac.Held/CM4Documentation/GFDL-CM4.0/inputData/CM4_runDir.tar.gz and was able to unzip and untar with `tar -zxvf CM4_runDir.tar.gz`.  Have you tried to unzip and untar a different file?

**Comment by miniufo** [comment]
I asked one of my collegues to download and untar it.  It failed when using winrar on Windows platform, but somehow succeeded on Linux platform.  It is still strange to me but I think I worked it out now.  Thanks very much @thomas-robinson
